"""
Test compatibility between original dingo and refactored dingo-waveform.

This test suite compares waveforms generated by both packages to ensure
the refactoring preserves scientific correctness.
"""
import pytest
import numpy as np

from dingo_waveform.comparison import compare_waveforms


# Shared test parameters
@pytest.fixture
def base_waveform_params():
    """Basic waveform parameters for testing."""
    return {
        "mass_1": 36.0,
        "mass_2": 29.0,
        "chirp_mass": 28.095556,
        "mass_ratio": 0.805556,
        "luminosity_distance": 1000.0,
        "theta_jn": 0.5,
        "phase": 0.0,
        "a_1": 0.0,
        "a_2": 0.0,
        "tilt_1": 0.0,
        "tilt_2": 0.0,
        "phi_12": 0.0,
        "phi_jl": 0.0,
        "geocent_time": 0.0,
    }


@pytest.fixture
def uniform_domain_params():
    """UniformFrequencyDomain parameters."""
    return {
        "delta_f": 0.125,
        "f_min": 20.0,
        "f_max": 1024.0,
    }


@pytest.fixture
def multibanded_domain_params():
    """MultibandedFrequencyDomain parameters."""
    return {
        "nodes": [20.0, 26.0, 34.0, 46.0, 62.0, 78.0, 1038.0],
        "delta_f_initial": 0.0625,
        "base_delta_f": 0.0625,
    }


class TestUniformFrequencyDomainCompatibility:
    """Test waveform generation with UniformFrequencyDomain."""

    @pytest.mark.parametrize(
        "approximant",
        ["IMRPhenomD", "IMRPhenomXAS", "IMRPhenomXPHM"],
    )
    def test_ufd_lal_approximants(
        self, uniform_domain_params, base_waveform_params, approximant
    ):
        """Test LAL approximants produce identical results."""
        result = compare_waveforms(
            domain_type="uniform",
            domain_params=uniform_domain_params,
            approximant=approximant,
            waveform_params=base_waveform_params,
            f_ref=20.0,
            f_start=20.0,
        )

        # Shapes must match
        assert result.shapes_match, (
            f"Shape mismatch for {approximant}: "
            f"dingo={result.dingo_shape}, refactored={result.refactored_shape}"
        )

        # Waveforms should be numerically identical (or very close)
        assert result.max_diff_h_plus < 1e-20, (
            f"h_plus difference too large for {approximant}: {result.max_diff_h_plus}"
        )
        assert result.max_diff_h_cross < 1e-20, (
            f"h_cross difference too large for {approximant}: {result.max_diff_h_cross}"
        )


class TestMultibandedFrequencyDomainCompatibility:
    """Test waveform generation with MultibandedFrequencyDomain."""

    @pytest.mark.parametrize(
        "approximant",
        ["IMRPhenomXPHM"],
    )
    def test_mfd_native_fd_approximants(
        self, multibanded_domain_params, base_waveform_params, approximant
    ):
        """Test native frequency-domain approximants with MFD."""
        result = compare_waveforms(
            domain_type="multibanded",
            domain_params=multibanded_domain_params,
            approximant=approximant,
            waveform_params=base_waveform_params,
            f_ref=10.0,
            f_start=10.0,
        )

        # Shapes must match
        assert result.shapes_match, (
            f"Shape mismatch for {approximant}: "
            f"dingo={result.dingo_shape}, refactored={result.refactored_shape}"
        )

        # Both should return MFD-sized waveforms (736 bins for these nodes)
        assert result.dingo_shape == (736,), f"Unexpected dingo shape: {result.dingo_shape}"
        assert result.refactored_shape == (736,), f"Unexpected refactored shape: {result.refactored_shape}"

        # Waveforms should be very close
        assert result.max_diff_h_plus < 1e-20, (
            f"h_plus difference too large for {approximant}: {result.max_diff_h_plus}"
        )
        assert result.max_diff_h_cross < 1e-20, (
            f"h_cross difference too large for {approximant}: {result.max_diff_h_cross}"
        )

    @pytest.mark.parametrize(
        "approximant",
        ["SEOBNRv5PHM", "SEOBNRv5HM"],
    )
    def test_mfd_time_domain_approximants(
        self, multibanded_domain_params, base_waveform_params, approximant
    ):
        """Test time-domain approximants with MFD."""
        result = compare_waveforms(
            domain_type="multibanded",
            domain_params=multibanded_domain_params,
            approximant=approximant,
            waveform_params=base_waveform_params,
            f_ref=10.0,
            f_start=10.0,
        )

        # Shapes must match
        assert result.shapes_match, (
            f"Shape mismatch for {approximant}: "
            f"dingo={result.dingo_shape}, refactored={result.refactored_shape}"
        )

        # Both should return MFD-sized waveforms
        assert result.dingo_shape == (736,), f"Unexpected dingo shape: {result.dingo_shape}"
        assert result.refactored_shape == (736,), f"Unexpected refactored shape: {result.refactored_shape}"

        # Waveforms should be very close
        assert result.max_diff_h_plus < 1e-20, (
            f"h_plus difference too large for {approximant}: {result.max_diff_h_plus}"
        )
        assert result.max_diff_h_cross < 1e-20, (
            f"h_cross difference too large for {approximant}: {result.max_diff_h_cross}"
        )


class TestDomainProperties:
    """Test that domain properties match between implementations."""

    def test_ufd_properties(self, uniform_domain_params):
        """Test UniformFrequencyDomain properties match."""
        from dingo_waveform.comparison import (
            create_uniform_domain_dingo,
            create_uniform_domain_refactored,
        )

        dingo_domain = create_uniform_domain_dingo(**uniform_domain_params)
        refactored_domain = create_uniform_domain_refactored(**uniform_domain_params)

        assert len(dingo_domain) == len(refactored_domain)
        assert abs(dingo_domain.f_min - refactored_domain.f_min) < 1e-10
        assert abs(dingo_domain.f_max - refactored_domain.f_max) < 1e-10
        assert abs(dingo_domain.delta_f - refactored_domain.delta_f) < 1e-10

    def test_mfd_properties(self, multibanded_domain_params):
        """Test MultibandedFrequencyDomain properties match."""
        from dingo_waveform.comparison import (
            create_multibanded_domain_dingo,
            create_multibanded_domain_refactored,
        )

        dingo_domain = create_multibanded_domain_dingo(**multibanded_domain_params)
        refactored_domain = create_multibanded_domain_refactored(**multibanded_domain_params)

        assert len(dingo_domain) == len(refactored_domain)
        assert abs(dingo_domain.f_min - refactored_domain.f_min) < 1e-10
        assert abs(dingo_domain.f_max - refactored_domain.f_max) < 1e-10
